[package]
name = "meantime"
version = "1.0.0"
edition = "2021"
license = "THE-BEER-WARE-LICENSE"
categories = ["command-line-utilities"]

[profile.dev]
debug = 1
panic = "abort"
opt-level = 1
incremental = true
overflow-checks = true

[build]
rustc-wrapper = "rustc -C prefer-dynamic"
